### ISSUE TITLE
Use Mengpaneel in a Mailer

### ISSUE THREAD

**Issue by jankeesvw** [DouweM/mengpaneel#4]
Hi @DouweM, I'm considering to add `track` calls to my mailers so I can track if the mails we send affect the usage of our app. 

Can you describe how I can use Mengpaneel in a mailer? Thanks!

**Comment by DouweM** [comment]
Hi Jankees,

What kind of events are you looking to track? The email having been opened or a link in the email having been clicked?

**Comment by jankeesvw** [comment]
I would like to track the emails I send, to see the relation between the send emails and the usage of our application.

**Comment by DouweM** [comment]
Please forgive me for the long delay in responding! 

Mengpaneel doesn't do anything special for mailers, but you can get to Mengpaneel directly like this: (quoting from the readme):

> Finally, if you want to track events from a script or background worker instead of a controller, you can use Mengpaneel::Manager directly, like this:
> 
> ```ruby
> class SubscriptionRenewalWorker
>   include Sidekiq::Worker
> 
>   def perform(subscription_id)
>     subscription = Subscription.find(subscription_id)
> 
>     subscription.renew!
> 
>     Mengpaneel::Manager.new do |mengpaneel|
>       mengpaneel.setup do |mixpanel|
>         mixpanel.identify(subscription.user.id)
>       end
> 
>       # Because the `mixpanel` method exposed in your controllers isn't 
>       # available here, you need to get it explicitly from Mengpaneel.
>       mengpaneel.tracking do |mixpanel|
>         mixpanel.track("Renew Subscription", "Subscription ID" => subscription.id)
>       end
>     end
>   end
> end
> ```

You can put the `Mengpaneel::Manager` stuff in your mailer method.
