### ISSUE TITLE
Still maintaining this?

### ISSUE THREAD

**Issue by hpoydar** [DouweM/mengpaneel#5]
Looks like a great gem - just wondering if it's still being actively used in production. (The mixpanel-ruby gem seems ahead of this gem.)

**Comment by DouweM** [comment]
Mengpaneel is still being used in production at Stinngo.com. It's still being maintained, but it already does everything we want to it to, so there hasn't really been anything to maintain these past few months :)

The mixpanel-ruby gem serves a very different purpose from Mengpaneel, so it's not really "ahead" in any sense. mixpanel-ruby is simply a Ruby client for the Mixpanel API, which allows you to send events from server-side processes. Mengpaneel allows you to specify events in your Rails controllers, that are then sent out to Mixpanel using the most convenient mechanism, which is often actually injecting the corresponding JS event code into the HTML source of the page. It solves a bunch of problems that are all described in the readme.
